#!/bin/bash
#Author by Yifeng Han

# Create certificate
cd /data/key_files
ipsec pki --gen --outform pem > ca.pem
ipsec pki --self --in ca.pem --dn "C=$CERT_C, O=$CERT_O, CN=$CERT_CN" --ca --lifetime 3650 --outform pem >ca.cert.pem
ipsec pki --gen --outform pem > server.pem
ipsec pki --gen --outform pem > client.pem
ipsec pki --pub --in server.pem | ipsec pki --issue --lifetime 1200 --cacert ca.cert.pem --cakey ca.pem --dn "C=$CERT_C, O=$CERT_O, CN=$HOSTIP" --san="$HOSTIP" --flag serverAuth --flag ikeIntermediate --outform pem > server.cert.pem
ipsec pki --pub --in client.pem | ipsec pki --issue --cacert ca.cert.pem --cakey ca.pem --dn "C=$CERT_C, O=$CERT_O, CN=$CERT_CN client" --outform pem > client.cert.pem
